### PR TITLE
Added Google account authorization, setup contacts import/whitelisting, automatic forwarding for Squadbox

### PR DESCRIPTION
**Pull request by oliverjd**
Issue #110

### CODE REVIEW

**Comment by amyxzhang** [comment]
@oliverjd having the gmail client secrets here in the public Github is unsecure. Can you create new ones and send them to us like via email to put into our separate private.py files? Then the code can reference it from settings.py. You might also want to add that instruction to the readme.txt for people just getting started.

**Comment by amyxzhang** [comment]
Also it seems like the squadbox and murmur templates for gmail forwarding right now are the same? I can't tell for sure. If that's the case then I don't think we should duplicate them.

**Comment by kmahar** [comment]
well I think the difference is that one uses murmur's base template, and one uses squadbox's? 

for shared templates we could consider having some third folder "shared", and then send a variable in HTTP response indicating which base template to use.

**Comment by oliverjd** [comment]
The HTML files are actually different as we don't setup the forwarding filter for Murmur but we do for Squadbox.

**Comment by amyxzhang** [comment]
right. in django, templates can extend upon templates. There should be a way to do this so that squadbox-specific stuff can be in its own template and common things are in a common template.

**Comment by kmahar** [comment]
Ok. Let's put shared stuff in top level (templates/) and then the specific ones under templates/squadbox/ and templates/murmur/ folders, then?

**Comment by kmahar** [comment]
For now don't worry about deleting the duplicates, probably easier to just clean up/remove the unneeded files as we update each page.

**Comment by oliverjd** [comment]
Do you want me to do that now?

**Comment by kmahar** [comment]
I would just do it for the files involved in this PR and leave the rest for now... I'm working on some template changes myself right now so I don't want to have conflicts with those later on

**Comment by oliverjd** [comment]
Done

**Pull request merged**
