### PR TITLE
Attachment upload using Amazon S3

### PR DESCRIPTION
**Pull request by oliverjd**
Issue #116 
- Updated Django to 1.6.11 for compatibility with django-storages (it's backwards compatible with 1.6.1)
- Added dependencies to requirements.txt for AWS access
- Incoming mail with allowed attachments will be uploaded to S3
- Updated schema to include attachments table storing SHA-1 hash and filenames
- Web UI now shows attachments (if any) and links to internal URL which is redirected by a view to S3

### CODE REVIEW

**Comment by amyxzhang** [comment]
@oliverjd can you send me the s3 info privately? also, did you have to provide a payment option at all? It would be nice to move that under haystack so that you aren't charged at any point.

Also, just checking - how is privacy handled with regards to s3 urls?

**Comment by oliverjd** [comment]
Updated; now uploads files as private and generates secure temporary URL on request if the user is allowed to view the message that the attachment is associated with

**Comment by oliverjd** [comment]
Updated; issue #122 
- added option for user to decide if they want to receive attachments on a per-group basis

**Comment by amyxzhang** [comment]
Really sorry @oliverjd for holding off on this. If you could resolve this conflict, then I will merge in this pull request right after. Thank you!

**Pull request merged**
