### PR TITLE
Send "unsubscribe" to unsubscribe

### PR DESCRIPTION
**Pull request by kmahar**
If you send a message that starts with "subscribe" or "unsubscribe" followed by the newline character, the message handling will be transferred to the relevant route and you will subscribe/unsubscribe to the group. Fixes issue #51 

Those routes were not actually working (the function calls passed in the email address rather than the user object) so I fixed them. I ended up just copy-pasting in the try/except from another part of main.py. From what I can tell, in every part of the code where subscribe_group or unsubscribe_group is called, the call is preceded by a similar try/except (or get_object_or_404) to get the user via their email address. It might make sense to have the functions just take in the email address rather than user, and if the user is not found the function can return an appropriate error message. They already do some error handling for group not found, anyway.

### CODE REVIEW

**Comment by karger** [comment]
I'd recommend being a little careful about doing such a significant
action based on a single email. Perhaps an unsubscribe message should
generate a request for confirmation or something like? 

Also, what protection doing we have against someone forging "from"
headers in order to unsubscribe someone else?

**Comment by kmahar** [comment]
Ok, I think it might be easiest to implement that as follows: if you send a message to group_name@murmur saying "unsubscribe", we send you an email from (or with a reply-to field of) group_name+unsubscribe@murmur that says, "reply to this message to confirm." (via the unsubscribe route, sending any message back to group_name+unsubscribe would unsubscribe you.) Then we don't actually have to keep track of who has a pending unsubscribe request out, or anything like that. Does that sound reasonable?

As for protection, I just get the "from" address in the same way it is gotten for a normal post, with parseaddr on the message's "from" field, and match that to a user. So there is really nothing at the moment. I can work on that. (Is there anything currently in place to check that a normal post to the group doesn't have a forged header?)

**Comment by karger** [comment]
one easy option is to let users disable "command through email" if they want
a harder but more useful one would be to configure to only accept emails
from them that are pgp-signed.

**Comment by amyxzhang** [comment]
AFAIK there isn't an *easy* way to check for forged headers. There are lots of hard/not-fail-safe methods: http://security.stackexchange.com/questions/30732/why-is-it-even-possible-to-forge-sender-header-in-e-mail 

I think it would be better if they've subscribed or unsubscribed in any way (via email or web) to send an email that says something to the effect of "You've unsubscribed/subscribed to this mailing list. Click here/Reply with blah to undo your action"  I think I would personally be annoyed to have to write two emails to unsubscribe. I also think this way is more common in other applications I've seen.

**Comment by amyxzhang** [comment]
Also, what if they write unsubscribe without a newline (and it's the entire email)? I think that should also trigger an action.

**Comment by karger** [comment]
Well, if they have to click to resubscribe, it gives trolls a great 
opportunity to force users to do an unlimited amount of resubscription work.

**Comment by amyxzhang** [comment]
Right, well if they're spoofing email headers, they can certainly wreck havoc in many other ways too. So email header spoofing is a bigger issue. I'll open up a ticket for implementing SPF-checking which should be a good way to make it at least a little more difficult for people to do this. 

But for this issue, I'd prefer to do what feels best to the user in the general use case, as opposed to potential problems that are not yet pressing.

**Comment by karger** [comment]
So an interesting question is: since any sufficiently popular service 
that permits this attack is bound to be suffering from it, how do they 
protect against it?

**Comment by amyxzhang** [comment]
From googling around, it looks like most places (such as gmail) are looking up SPF and DKIM records. I opened ticket #62 for this.

**Comment by kmahar** [comment]
Ok, so what updates should I make then? I can make the "you've unsubscribed" email be a little more informative, and add an option to "undo" your un-subscription by replying? 

I will make the fix for a message containing only "unsubscribe" (no newline) as well.

**Comment by amyxzhang** [comment]
I am personally leaning towards the "You've unsubscribed" email with an
undo option, but if you have reasons against it, feel free to express them!

On Tue, Feb 2, 2016 at 12:25 AM, Kaitlin Mahar <notifications@github.com>
wrote:

> Ok, so what updates should I make then? I can make the "you've
> unsubscribed" email be a little more informative, and add an option to
> "undo" your un-subscription by replying?
>
> I will make the fix for a message containing only "unsubscribe" (no
> newline) as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/murmur/pull/61#issuecomment-178383238>.
>



-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh

**Comment by kmahar** [comment]
No, I think that sounds fine.

**Comment by kmahar** [comment]
I have set the reply-to address for the confirmation email to be group_name+subscribe@murmur, so sending any reply, regardless of content, to the unsubscription confirmation will resubscribe you to the list. Right now the confirmation just says - "You are now unsubscribed from x. To resubscribe, reply to this email." Do you think that will be confusing for people? They might wonder what the reply is supposed to say.

**Comment by kmahar** [comment]
I tried to add an unsubscribe link to the HTML email signature, but I don't think there is actually a URL you can just go to and unsubscribe. you have to send a post request with the group name to /unsubscribe_group. I guess we could just make it a mailto link, but it's inconsistent with all the other links in the signature.

**Comment by amyxzhang** [comment]
Yeah you'll want to add a new endpoint. You can look at the mute, follow,
or upvote endpoints for examples.

On Thursday, February 18, 2016, Kaitlin Mahar <notifications@github.com>
wrote:

> I tried to add an unsubscribe link to the HTML email signature, but I
> don't think there is actually a URL you can just go to and unsubscribe. you
> have to send a post request with the group name to /unsubscribe_group. I
> guess we could just make it a mailto link, but it's inconsistent with all
> the other links in the signature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/murmur/pull/61#issuecomment-185905137>.
>


-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh

**Comment by kmahar** [comment]
I've added unsubscribe/subscribe endpoints. There is now a link in the HTML email signatures to the unsubscribe endpoint (and the URL is included in the plaintext signature as well.) the unsubscribe endpoint has a "resubscribe" button that takes you to the subscribe endpoint, and vice versa. As I mentioned in #70 the existence of these endpoints isn't very secure at the moment, but I can work on that

**Pull request merged**
